  application: pdg
  version: 1
  runtime: python27
  api_version: 1
  threadsafe: yes

  handlers:

  - url: /(.+)
    static_files: public/\1
    upload: public/(.*)

  - url: /bower_components/(.+)
    static_files: public/bower_components/\1
    upload: public/bower_components/(.*)

  - url: /elements/(.+)
    static_files: public/elements/\1
    upload: public/elements/(.*)

  - url: /src/(.+)
    static_files: public/src/\1
    upload: public/src/(.*)

  - url: /data/(.+)
    static_files: public/data/\1
    upload: public/data/(.*)

  - url: /sw-import.js
    static_files: public/sw-import.js
    upload: public/sw-import.js

  - url: /elements.html
    static_files: public/elements.html
    upload: public/elements.html

  - url: /build.html
    static_files: public/build.html
    upload: public/build.html

  - url: /
    static_files: public/index.html
    upload: public/index.html

  - url: /speaker.*
    static_files: public/index.html
    upload: public/index.html

  - url: /agenda.*
    static_files: public/index.html
    upload: public/index.html

  - url: /getting.*
    static_files: public/index.html
    upload: public/index.html


  skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
